RDISCROWD-7850 - update 403 error for authorized services
bloomberg/pybossa pull request #1021
Opened 2024-12-20 21:25 UTC by peterkle

*Issue number of the reported bug or feature request: #RDISCROWD-7850*

2024-12-23 15:16 UTC, dchhabda approved these changes

2024-12-23 15:17 UTC, dchhabda requested changes
Overall looks good. Can you update settings_local.py.tmpl so that it has an example of what the new config `AUTHORIZED_SERVICES_403`. Thanks!

2024-12-23 16:13 UTC, peterkle commented
@dchhabda done!

2024-12-23 16:14 UTC, dchhabda approved these changes

2024-12-23 16:14 UTC, dchhabda commented
can be merged upon tests pass. Thank you!

2024-12-23 16:38 UTC, merged

2025-01-10 17:48 UTC, kbecker42 commented on pybossa/api/__init__.py
> +        authorized_services_403 = current_app.config.get("AUTHORIZED_SERVICES_403", "")
It would be helpful to include a default error message here, including placeholders for project_id and service_name in case the config is ever missing the expected value. This way, users would still receive a reasonable error message.