RDISCROWD-3853 Show row number upon csv import ASCII error
bloomberg/pybossa pull request #749
Opened 2022-06-22 18:17 UTC by kbecker42

- Added the row number to the error message when a csv file fails to import due to a non-ASCII character unicode error.

2022-06-22 22:04 UTC, dchhabda commented on pybossa/importers/csv.py
> +                        return (line_number, s)
With exception raised, `s` won't be available and line 366 would result into another exception suppressing the real exception caused by line 364. Also, logging exception would be useful before line 366.

2022-06-22 22:05 UTC, dchhabda requested changes
Please add tests to improve coverage. Thanks!

2022-06-23 18:16 UTC, kbecker42 commented
Fixed via https://github.com/bloomberg/pybossa/pull/749/commits/bcfb312c560b0b67332157f2678c224f36eb84a8

2022-06-23 18:17 UTC, kbecker42 commented on pybossa/importers/csv.py
> +                        return (line_number, s)
Fixed via https://github.com/bloomberg/pybossa/pull/749/commits/bcfb312c560b0b67332157f2678c224f36eb84a8

2022-06-27 14:18 UTC, merged